apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
    type: devops-statefulset
  ports:
  - name: mongo
    protocol: TCP
    port: 27017
    targetPort: 27017
  clusterIP: None

