apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: external-secrets

spec:
  secretStoreRef:
    name: aws-store
    kind: SecretStore

  target:
    name: db-secret

  data:
    - secretKey: DB_HOST
      remoteRef:
        key: ecommerce-db-secret
        property: DB_HOST

    - secretKey: DB_USER
      remoteRef:
        key: ecommerce-db-secret
        property: DB_USER

    - secretKey: DB_PASSWORD
      remoteRef:
        key: ecommerce-db-secret
        property: DB_PASSWORD

    - secretKey: DB_NAME
      remoteRef:
        key: ecommerce-db-secret
        property: DB_NAME

    - secretKey: DB_PORT
      remoteRef:
        key: ecommerce-db-secret
        property: DB_PORT